import 'package:comento_design_system/comento_design_system.dart';
import 'package:flutter/material.dart';

class CustomIconsHelper {
  CustomIconsHelper._();

  ///
  /// IconAlarmLargeLine 형식의 string을 받아서
  /// CustomIconData를 돌려주는 method
  ///
  static IconData getIcon(String icon) {
    final lowerCaseIcon = icon.toLowerCase();
    switch (lowerCaseIcon) {
      case 'iconalarmanswer':
        return CustomIcons.iconAlarmAnswer;
      case 'iconalarmassignment':
        return CustomIcons.iconAlarmAssignment;
      case 'iconalarmcelebrate':
        return CustomIcons.iconAlarmCelebrate;
      case 'iconalarmcreditplus':
        return CustomIcons.iconAlarmCreditPlus;
      case 'iconalarmlargeline':
        return CustomIcons.iconAlarmLargeLine;
      case 'iconalarmlike':
        return CustomIcons.iconAlarmLike;
      case 'iconalarmnotice':
        return CustomIcons.iconAlarmNotice;
      case 'iconalarmquestion':
        return CustomIcons.iconAlarmQuestion;
      case 'iconalarmselected':
        return CustomIcons.iconAlarmSelected;
      case 'iconalarmwon':
        return CustomIcons.iconAlarmWon;
      case 'iconanalyticslargeline':
        return CustomIcons.iconAnalyticsLargeLine;
      case 'iconanalyticsmediumline':
        return CustomIcons.iconAnalyticsMediumLine;
      case 'iconanalyticsxlargeline':
        return CustomIcons.iconAnalyticsXlargeLine;
      case 'iconanswer2xlargeline':
        return CustomIcons.iconAnswer_2xlargeLine;
      case 'iconanswerlargeline':
        return CustomIcons.iconAnswerLargeLine;
      case 'iconanswerxlargeline':
        return CustomIcons.iconAnswerXlargeLine;
      case 'iconArrowlargeline':
        return CustomIcons.iconArrowLargeLine;
      case 'iconArrowmediumline':
        return CustomIcons.iconArrowMediumLine;
      case 'iconArrowsmallline':
        return CustomIcons.iconArrowSmallLine;
      case 'iconArrowxlargeline':
        return CustomIcons.iconArrowXlargeLine;
      case 'iconArrowRoundmediumline':
        return CustomIcons.iconArrowRoundMediumLine;
      case 'iconbackwardlargeline':
        return CustomIcons.iconBackwardLargeLine;
      case 'iconblockmediumline':
        return CustomIcons.iconBlockMediumLine;
      case 'iconboard2xlargeline':
        return CustomIcons.iconBoard_2xlargeLine;
      case 'iconbookMarklargefill':
        return CustomIcons.iconBookMarkLargeFill;
      case 'iconbookMarklargeline':
        return CustomIcons.iconBookMarkLargeLine;
      case 'iconbookMarkmediumfill':
        return CustomIcons.iconBookmarkMediumFill;
      case 'iconbookMarkmediumline':
        return CustomIcons.iconBookmarkMediumLine;
      case 'iconbookMarkxlargefill':
        return CustomIcons.iconBookMarkXlargeFill;
      case 'iconbookMarkxlargeline':
        return CustomIcons.iconBookMarkXlargeLine;
      case 'iconbrowsemediumfill':
        return CustomIcons.iconBrowseMediumFill;
      case 'iconbrowsemediumline':
        return CustomIcons.iconBrowseMediumLine;
      case 'iconchangejob2xlargeline':
        return CustomIcons.iconChangeJob_2xlargeLine;
      case 'iconchecklargeline':
        return CustomIcons.iconCheckLargeLine;
      case 'iconcheckmediumline':
        return CustomIcons.iconCheckMediumLine;
      case 'iconchecksmallline':
        return CustomIcons.iconCheckSmallLine;
      case 'iconcheckRound2xlargefill':
        return CustomIcons.iconCheckRound_2xlargeFill;
      case 'iconcheckRound2xlargeline':
        return CustomIcons.iconCheckRound_2xlargeLine;
      case 'iconcheckRoundlargefill':
        return CustomIcons.iconCheckRoundLargeFill;
      case 'iconcheckRoundlargeline':
        return CustomIcons.iconCheckRoundLargeLine;
      case 'iconcheckRoundmediumfill':
        return CustomIcons.iconCheckRoundMediumFill;
      case 'iconcheckRoundmediumline':
        return CustomIcons.iconCheckRoundMediumLine;
      case 'iconcheckRoundsmallfill':
        return CustomIcons.iconCheckRoundSmallFill;
      case 'iconcheckRoundsmallline':
        return CustomIcons.iconCheckRoundSmallLine;
      case 'iconcheckRoundxlargefill':
        return CustomIcons.iconCheckRoundXlargeFill;
      case 'iconcheckRoundxlargeline':
        return CustomIcons.iconCheckRoundXlargeLine;
      case 'iconclockmediumfill':
        return CustomIcons.iconClockMediumFill;
      case 'iconclockmediumline':
        return CustomIcons.iconClockMediumLine;
      case 'iconcloselargeline':
        return CustomIcons.iconCloseLargeLine;
      case 'iconclosemediumline':
        return CustomIcons.iconCloseMediumLine;
      case 'iconclosesmallline':
        return CustomIcons.iconCloseSmallLine;
      case 'iconclosexlargeline':
        return CustomIcons.iconCloseXlargeLine;
      case 'iconcloseRoundmediumfill':
        return CustomIcons.iconCloseRoundMediumFill;
      case 'iconcloseRoundmediumline':
        return CustomIcons.iconCloseRoundMediumLine;
      case 'iconcollege2xlargeline':
        return CustomIcons.iconCollege_2xlargeLine;
      case 'iconcommentmediumline':
        return CustomIcons.iconCommentMediumLine;
      case 'iconcouponlargeline':
        return CustomIcons.iconCouponLargeLine;
      case 'iconcouponmediumline':
        return CustomIcons.iconCouponMediumLine;
      case 'icondiscountmediumline':
        return CustomIcons.iconDiscountMediumLine;
      case 'icondownloadlargeline':
        return CustomIcons.iconDownloadLargeLine;
      case 'icondownloadmediumline':
        return CustomIcons.iconDownloadMediumLine;
      case 'icondownloadxlargeline':
        return CustomIcons.iconDownloadXlargeLine;
      case 'iconedulargefill':
        return CustomIcons.iconEduLargeFill;
      case 'iconedulargeline':
        return CustomIcons.iconEduLargeLine;
      case 'iconessaylargeline':
        return CustomIcons.iconEssayLargeLine;
      case 'iconessaymediumline':
        return CustomIcons.iconEssayMediumLine;
      case 'iconessayxlargeline':
        return CustomIcons.iconEssayXlargeLine;
      case 'iconexclamationlargefill':
        return CustomIcons.iconExclamationLargeFill;
      case 'iconexclamationlargeline':
        return CustomIcons.iconExclamationLargeLine;
      case 'iconexclamationmediumfill':
        return CustomIcons.iconExclamationMediumFill;
      case 'iconexclamationmediumline':
        return CustomIcons.iconExclamationMediumLine;
      case 'iconexclamationsmallfill':
        return CustomIcons.iconExclamationSmallFill;
      case 'iconexclamationsmallline':
        return CustomIcons.iconExclamationSmallLine;
      case 'iconexportmediumline':
        return CustomIcons.iconExportMediumLine;
      case 'iconfilemediumline':
        return CustomIcons.iconFileMediumLine;
      case 'iconfilesmallline':
        return CustomIcons.iconFileSmallLine;
      case 'iconfilterlargeline':
        return CustomIcons.iconFilterLargeLine;
      case 'iconfiltermediumline':
        return CustomIcons.iconFilterMediumLine;
      case 'iconhamburgerlargeline':
        return CustomIcons.iconHamburgerLargeLine;
      case 'iconimportlargeline':
        return CustomIcons.iconImportLargeLine;
      case 'iconimportmediumline':
        return CustomIcons.iconImportMediumLine;
      case 'iconinformationlargefill':
        return CustomIcons.iconInformationLargeFill;
      case 'iconinformationlargeline':
        return CustomIcons.iconInformationLargeLine;
      case 'iconinformationsmallfill':
        return CustomIcons.iconInformationSmallFill;
      case 'iconinformationsmallline':
        return CustomIcons.iconInformationSmallLine;
      case 'iconinterviewlargeline':
        return CustomIcons.iconInterviewLargeLine;
      case 'iconinterviewmediumline':
        return CustomIcons.iconInterviewMediumLine;
      case 'iconjob2xlargeline':
        return CustomIcons.iconJob_2xlargeLine;
      case 'iconlikemediumfill':
        return CustomIcons.iconLikeMediumFill;
      case 'iconlikemediumline':
        return CustomIcons.iconLikeMediumLine;
      case 'iconlikesmallfill':
        return CustomIcons.iconLikeSmallFill;
      case 'iconlikesmallline':
        return CustomIcons.iconLikeSmallLine;
      case 'iconlinklargeline':
        return CustomIcons.iconLinkLargeLine;
      case 'iconlinkmediumline':
        return CustomIcons.iconLinkMediumLine;
      case 'iconlinksmallline':
        return CustomIcons.iconLinkSmallLine;
      case 'iconlocationmediumfill':
        return CustomIcons.iconLocationMediumFill;
      case 'iconlocationmediumline':
        return CustomIcons.iconLocationMediumLine;
      case 'iconlocklargefill':
        return CustomIcons.iconLockLargeFill;
      case 'iconlocklargeline':
        return CustomIcons.iconLockLargeLine;
      case 'iconlockmediumfill':
        return CustomIcons.iconLockMediumFill;
      case 'iconlockmediumline':
        return CustomIcons.iconLockMediumLine;
      case 'iconmegaphonelargeline':
        return CustomIcons.iconMegaphoneLargeLine;
      case 'iconmegaphonemediumline':
        return CustomIcons.iconMegaphoneMediumLine;
      case 'iconmegaphonesmallline':
        return CustomIcons.iconMegaphoneSmallLine;
      case 'iconmentoringlargefill':
        return CustomIcons.iconMentoringLargeFill;
      case 'iconmentoringlargeline':
        return CustomIcons.iconMentoringLargeLine;
      case 'iconminusmediumline':
        return CustomIcons.iconMinusMediumLine;
      case 'iconphoto2xlargeline':
        return CustomIcons.iconPhoto_2xlargeLine;
      case 'iconphotolargeline':
        return CustomIcons.iconPhotoLargeLine;
      case 'iconphotoxlargeline':
        return CustomIcons.iconPhotoXlargeLine;
      case 'iconplus2xlargeline':
        return CustomIcons.iconPlus_2xlargeLine;
      case 'iconpluslargeline':
        return CustomIcons.iconPlusLargeLine;
      case 'iconplusmediumline':
        return CustomIcons.iconPlusMediumLine;
      case 'iconplussmallline':
        return CustomIcons.iconPlusSmallLine;
      case 'iconplusRoundlargeline':
        return CustomIcons.iconPlusRoundLargeLine;
      case 'iconplusRoundmediumline':
        return CustomIcons.iconPlusRoundMediumLine;
      case 'iconpricemediumline':
        return CustomIcons.iconPriceMediumLine;
      case 'iconprofile2xlargefill':
        return CustomIcons.iconProfile_2xlargeFill;
      case 'iconprofilelargefill':
        return CustomIcons.iconProfileLargeFill;
      case 'iconprofilelargeline':
        return CustomIcons.iconProfileLargeLine;
      case 'iconprofilesmallfill':
        return CustomIcons.iconProfileSmallFill;
      case 'iconprofilesmallline':
        return CustomIcons.iconProfileSmallLine;
      case 'iconprofilexlargefill':
        return CustomIcons.iconProfileXlargeFill;
      case 'iconprofilexlargeline':
        return CustomIcons.iconProfileXlargeLine;
      case 'iconptlargefill':
        return CustomIcons.iconPtLargeFill;
      case 'iconptlargeline':
        return CustomIcons.iconPtLargeLine;
      case 'iconquestionlargeline':
        return CustomIcons.iconQuestionLargeLine;
      case 'iconquestionmediumline':
        return CustomIcons.iconQuestionMediumLine;
      case 'iconquestionMarklargefill':
        return CustomIcons.iconQuestionMarkLargeFill;
      case 'iconquestionMarklargeline':
        return CustomIcons.iconQuestionMarkLargeLine;
      case 'iconquestionMarkmediumfill':
        return CustomIcons.iconQuestionMarkMediumFill;
      case 'iconquestionMarkmediumline':
        return CustomIcons.iconQuestionMarkMediumLine;
      case 'iconquestionMarksmallfill':
        return CustomIcons.iconQuestionMarkSmallFill;
      case 'iconquestionMarksmallline':
        return CustomIcons.iconQuestionMarkSmallLine;
      case 'iconreplylargeline':
        return CustomIcons.iconReplyLargeLine;
      case 'iconresumelargeline':
        return CustomIcons.iconResumeLargeLine;
      case 'iconresumemediumline':
        return CustomIcons.iconResumeMediumLine;
      case 'iconrevertmediumline':
        return CustomIcons.iconRevertMediumLine;
      case 'iconsearchlargeline':
        return CustomIcons.iconSearchLargeLine;
      case 'iconsearchsmallline':
        return CustomIcons.iconSearchSmallLine;
      case 'iconsecuritylargefill':
        return CustomIcons.iconSecurityLargeFill;
      case 'iconsecuritylargeline':
        return CustomIcons.iconSecurityLargeLine;
      case 'iconsendlargefill':
        return CustomIcons.iconSendLargeFill;
      case 'iconsettinglargeline':
        return CustomIcons.iconSettingLargeLine;
      case 'iconsettingsmallfill':
        return CustomIcons.iconSettingSmallFill;
      case 'iconsirenmediumline':
        return CustomIcons.iconSirenMediumLine;
      case 'iconstarlargefill':
        return CustomIcons.iconStarLargeFill;
      case 'iconstarlargeline':
        return CustomIcons.iconStarLargeLine;
      case 'iconstarmediumfill':
        return CustomIcons.iconStarMediumFill;
      case 'iconstarmediumline':
        return CustomIcons.iconStarMediumLine;
      case 'iconstarsmallfill':
        return CustomIcons.iconStarSmallFill;
      case 'iconstarsmallline':
        return CustomIcons.iconStarSmallLine;
      case 'iconstarxlargefill':
        return CustomIcons.iconStarXlargeFill;
      case 'iconstarxlargeline':
        return CustomIcons.iconStarXlargeLine;
      case 'iconstarRoundlargefill':
        return CustomIcons.iconStarRoundLargeFill;
      case 'iconsupervisor2xlargeline':
        return CustomIcons.iconSupervisor_2xlargeLine;
      case 'iconsupport2xlargeline':
        return CustomIcons.iconSupport_2xlargeLine;
      case 'iconsupportmediumline':
        return CustomIcons.iconSupportMediumLine;
      case 'iconsupportxlargeline':
        return CustomIcons.iconSupportXlargeLine;
      case 'icontextArrowlargeline':
        return CustomIcons.iconTextArrowLargeLine;
      case 'icontextArrowmediumline':
        return CustomIcons.iconTextArrowMediumLine;
      case 'icontextArrowsmallline':
        return CustomIcons.iconTextArrowSmallLine;
      case 'icontextArrowxlargeline':
        return CustomIcons.iconTextArrowXlargeLine;
      case 'iconthreedotlargefill':
        return CustomIcons.iconThreeDotLargeFill;
      case 'iconthreedotmediumfill':
        return CustomIcons.iconThreeDotMediumFill;
      case 'iconthreedotsmallfill':
        return CustomIcons.iconThreeDotSmallFill;
      case 'icontrashlargeline':
        return CustomIcons.iconTrashLargeLine;
      case 'icontrashmediumline':
        return CustomIcons.iconTrashMediumLine;
      case 'iconunblockmediumline':
        return CustomIcons.iconUnblockMediumLine;
      case 'iconvideolargefill':
        return CustomIcons.iconVideoLargeFill;
      case 'iconvideolargeline':
        return CustomIcons.iconVideoLargeLine;
      case 'iconvideomediumfill':
        return CustomIcons.iconVideoMediumFill;
      case 'iconvideomediumline':
        return CustomIcons.iconVideoMediumLine;
      case 'iconvodlargeline':
        return CustomIcons.iconVodLargeLine;
      case 'iconvodmediumline':
        return CustomIcons.iconVodMediumLine;
      case 'iconvodxlargeline':
        return CustomIcons.iconVodXlargeLine;
      case 'iconvodproductlargeline':
        return CustomIcons.iconVodproductLargeLine;
      case 'iconwriting2xlargeline':
        return CustomIcons.iconWriting_2xlargeLine;
      case 'iconwritinglargeline':
        return CustomIcons.iconWritingLargeLine;
      case 'iconwritingmediumline':
        return CustomIcons.iconWritingMediumLine;
      case 'iconwritingsmallline':
        return CustomIcons.iconWritingSmallLine;
      case 'iconclasslargeline':
        return CustomIcons.iconClassLargeLine;
      case 'iconbusinesscaselargeline':
        return CustomIcons.iconBusinessCaseLargeLine;
      case 'iconfeedlargeline':
        return CustomIcons.iconFeedLargeLine;
      default:
        return Icons.error;
    }
  }
}
