name: comento_design_system
description: Comento Design System and UI components for Comento applications built on Flutter.
version: 0.0.24
homepage: https://comento.kr

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  super_tooltip: ^1.0.1
  flutter_styled_toast: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/icons/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf