name: comento_design_system
description: Comento Design System and UI components for Comento applications built on Flutter.
version: 0.0.3
homepage: https://comento.kr

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: SpoqaHanSans
      fonts:
        - asset: assets/fonts/SpoqaHanSansBold.ttf
          weight: 700
        - asset: assets/fonts/SpoqaHanSansRegular.ttf
          weight: 400
        - asset: assets/fonts/SpoqaHanSansLight.ttf
          weight: 300
        - asset: assets/fonts/SpoqaHanSansThin.ttf
          weight: 100