name: comento_design_system
description: Comento Design System and UI components for Comento applications built on Flutter.
version: 0.0.7
homepage: https://comento.kr

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  super_tooltip: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/icons/
  fonts:
    - family: SpoqaHanSans
      fonts:
        - asset: assets/fonts/SpoqaHanSansBold.ttf
          weight: 700
        - asset: assets/fonts/SpoqaHanSansRegular.ttf
          weight: 400
        - asset: assets/fonts/SpoqaHanSansLight.ttf
          weight: 300
        - asset: assets/fonts/SpoqaHanSansThin.ttf
          weight: 100