name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
        working-directory: .
      - run: |
          cd build/web
          git init
          git config --global user.email tech@comento.kr
          git config --global user.name comento
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/comento/flutter-comento-ui.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
